In [1]:
# minmaxscaler

In [2]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
print ("data=",data)
scaler = MinMaxScaler(feature_range = (10, 105.1))
print("fit=",scaler.fit(data))
print("data_max_=",scaler.data_max_)
print("data_min_=",scaler.data_min_)
print("transform",scaler.transform(data))

print ()
data = [[-1, ], [-0.5, ], [0, ], [1, ]]
print ("data=",data)
scaler = MinMaxScaler(feature_range = (10, 105.1))
print("fit=",scaler.fit(data))
print("data_max_=",scaler.data_max_)
print("data_min_=",scaler.data_min_)
print("transform",scaler.transform(data))

data= [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
fit= MinMaxScaler(feature_range=(10, 105.1))
data_max_= [ 1. 18.]
data_min_= [-1.  2.]
transform [[ 10.     10.   ]
 [ 33.775  33.775]
 [ 57.55   57.55 ]
 [105.1   105.1  ]]

data= [[-1], [-0.5], [0], [1]]
fit= MinMaxScaler(feature_range=(10, 105.1))
data_max_= [1.]
data_min_= [-1.]
transform [[ 10.   ]
 [ 33.775]
 [ 57.55 ]
 [105.1  ]]

In [3]:
#! pip install Faker==2.0.5

In [ ]:
# Pydb

In [6]:
import os
import random
from random import randint, choice
import pandas as pd
from six import moves
import ssl
from faker import Faker


class Pydb:
    def __init__(self, seed=None):
        """
        Initiates the class and creates a Faker() object for later data generation by other methods
        seed: User can set a seed parameter to generate deterministic, non-random output
        """
        

        self.faker = Faker()
        self.fake = Faker()
        self.seed = seed
        self.randnum = randint(1, 9)

        self.city_list = self._initialize_city_list()
        self.domain_list = self._initialize_email_domain_list()

    def _initialize_city_list(self):
        

        path = "../data/US_Cities.txt"
        if not os.path.isfile(path):
            context = ssl._create_unverified_context()
            moves.urllib.request.urlretrieve(
                "https://raw.githubusercontent.com/tflearn/tflearn.github.io/master/resources/US_Cities.txt",
                path,
            )

        city_list = []
        with open(path) as fh:
            city_list = [str(line).strip() for line in fh.readlines()]

        return city_list

    def _initialize_email_domain_list(self):
        dir_path = "../data"
        path = dir_path + os.sep + "Domains.txt"

        domain_list = []
        with open(path) as fh:
            domain_list = [str(line).strip() for line in fh.readlines()]

        return domain_list

    def simple_ph_num(self, seed=None):
        """
        Generates 10 digit US phone number in xxx-xxx-xxxx format
        seed: Currently not used. Uses seed from the pydb class if chosen by user
        """
        random.seed(self.seed)

        phone_format = "{p1}-{p2}-{p3}"

        p1 = str(randint(100, 999))
        p2 = str(randint(0, 999)).rjust(3, "0")
        p3 = str(randint(0, 9999)).rjust(4, "0")

        return phone_format.format(p1=p1, p2=p2, p3=p3)

    def license_plate(self, seed=None, style=None):
        """
        Generates vehicle license plate number in 3 possible styles
        Style can be 1, 2, or 3.
        - 9ABC123 format
        - ABC-1234 format
        - ABC-123 format
        If style is not specified by user, a random style is chosen at runtime
        seed: Currently not used. Uses seed from the pydb class if chosen by user
        """
        random.seed(self.seed)

        if not style:
            style = choice([1, 2, 3])

        license_place_format = "{p1}{p2}{p3}"

        if style == 1:
            p1 = str(randint(1, 9))
            p2 = "".join([chr(randint(65, 90)) for _ in range(3)])
            p3 = "".join([str(randint(1, 9)) for _ in range(3)])
        elif style == 2:
            p1 = "".join([chr(randint(65, 90)) for _ in range(3)])
            p2 = "-"
            p3 = "".join([str(randint(0, 9)) for _ in range(4)])
        else:
            p1 = "".join([chr(randint(65, 90)) for _ in range(3)])
            p2 = "-"
            p3 = "".join([str(randint(0, 9)) for _ in range(3)])

        return license_place_format.format(p1=p1, p2=p2, p3=p3)

    def realistic_email(self, name, seed=None):
        """
        Generates realistic email from first and last name and a random domain address
        seed: Currently not used. Uses seed from the pydb class if chosen by user
        """
        random.seed(self.seed)

        name = str(name)
        f_name = name.split()[0]
        l_name = name.split()[-1]

        choice_int = choice(range(10))

        domain = choice(self.domain_list)

        name_formats = [
            "{f}{last}",
            "{first}{last}",
            "{first}.{l}",
            "{first}_{l}",
            "{first}.{last}",
            "{first}_{last}",
            "{last}_{first}",
            "{last}.{first}",
        ]
        name_fmt_choice = choice(name_formats)
        name_combo = name_fmt_choice.format(
            f=f_name[0], l=l_name[0], first=f_name, last=l_name
        )

        if choice_int < 7:
            email = name_combo + "@" + str(domain)
        else:
            random_int = randint(11, 99)
            email = name_combo + str(random_int) + "@" + str(domain)

        return email

    def city_real(self, seed=None):
        """
        Picks and returns a random entry out of 385 US cities
        seed: Currently not used. Uses seed from the pydb class if chosen by user
        """
        random.seed(self.seed)

        return choice(self.city_list)

    def gen_data_series(self, num=10, data_type="name", seed=None):
        """
        Returns a pandas series object with the desired number of entries and data type

        Data types available:
        - Name, country, city, real (US) cities, US state, zipcode, latitude, longitude
        - Month, weekday, year, time, date
        - Personal email, official email, SSN
        - Company, Job title, phone number, license plate

        Phone number can be two types:
        'phone_number_simple' generates 10 digit US number in xxx-xxx-xxxx format
        'phone_number_full' may generate an international number with different format

        seed: Currently not used. Uses seed from the pydb class if chosen by user

        """
        if type(data_type) != str:
            raise ValueError(
                "Data type must be of type str, found " + str(type(data_type))
            )
        try:
            num = int(num)
        except:
            raise ValueError(
                "Number of samples must be a positive integer, found " + num
            )

        if num <= 0:
            raise ValueError(
                "Number of samples must be a positive integer, found " + num
            )

        num = int(num)
        fake = self.fake
        self.faker.seed(self.seed)

        func_lookup = {
            "name": fake.name,
            "country": fake.country,
            "street_address": fake.street_address,
            "city": fake.city,
            "real_city": self.city_real,
            "state": fake.state,
            "zipcode": fake.zipcode,
            "latitude": fake.latitude,
            "longitude": fake.longitude,
            "name_month": fake.month_name,
            "weekday": fake.day_of_week,
            "year": fake.year,
            "time": fake.time,
            "date": fake.date,
            "ssn": fake.ssn,
            "email": fake.email,
            "office_email": fake.company_email,
            "company": fake.company,
            "job_title": fake.job,
            "phone_number_simple": self.simple_ph_num,
            "phone_number_full": fake.phone_number,
            "license_plate": self.license_plate,
        }

        if data_type not in func_lookup:
            raise ValueError(
                "Data type must be one of " + str(list(func_lookup.keys()))
            )

        datagen_func = func_lookup[data_type]
        return pd.Series((datagen_func() for _ in range(num)))

    def _validate_args(self, num, fields):
        try:
            num = int(num)
        except:
            raise ValueError(
                "Number of samples must be a positive integer, found " + num
            )
        if num <= 0:
            raise ValueError(
                "Number of samples must be a positive integer, found " + num
            )

        num_cols = len(fields)
        if num_cols < 0:
            raise ValueError(
                "Please provide at least one type of data field to be generated"
            )

    def gen_dataframe(
        self,
        num=10,
        fields=["name"],
        real_email=True,
        real_city=True,
        phone_simple=True,
        seed=None,
    ):
        """
        Generate a pandas dataframe filled with random entries.
        User can specify the number of rows and data type of the fields/columns

        Data types available:
        - Name, country, city, real (US) cities, US state, zipcode, latitude, longitude
        - Month, weekday, year, time, date
        - Personal email, official email, SSN
        - Company, Job title, phone number, license plate

        Further choices are following:
        real_email: If True and if a person's name is also included in the fields, a realistic email will be generated corresponding to the name
        real_city: If True, a real US city's name will be picked up from a list. Otherwise, a fictitious city name will be generated.
        phone_simple: If True, a 10 digit US number in the format xxx-xxx-xxxx will be generated. Otherwise, an international number with different format may be returned.

        seed: Currently not used. Uses seed from the pydb class if chosen by user

        """
        self._validate_args(num, fields)

        df = pd.DataFrame(
            data=self.gen_data_series(num, data_type=fields[0]), columns=[fields[0]]
        )
        for col in fields[1:]:
            if col == "phone":
                if phone_simple:
                    df["phone-number"] = self.gen_data_series(
                        num, data_type="phone_number_simple"
                    )
                else:
                    df["phone-number"] = self.gen_data_series(
                        num, data_type="phone_number_full"
                    )
            elif col == "license_plate":
                df["license-plate"] = self.gen_data_series(num, data_type=col)
            elif col == "city" and real_city:
                df["city"] = self.gen_data_series(num, data_type="real_city")
            else:
                df[col] = self.gen_data_series(num, data_type=col)

        if ("email" in fields) and ("name" in fields) and real_email:
            df["email"] = df["name"].apply(self.realistic_email)

        return df

    def gen_table(
        self,
        num=10,
        fields=["name"],
        db_file=None,
        table_name=None,
        primarykey=None,
        real_email=True,
        real_city=True,
        phone_simple=True,
        seed=None,
    ):
        """
        Attempts to create a table in a database (.db) file using Python's built-in SQLite engine.
        User can specify various data types to be included as database table fields.
        All data types (fields) in the SQLite table will be of VARCHAR type.

        Data types available:
        - Name, country, city, real (US) cities, US state, zipcode, latitude, longitude
        - Month, weekday, year, time, date
        - Personal email, official email, SSN
        - Company, Job title, phone number, license plate

        Further choices are following:
        real_email: If True and if a person's name is also included in the fields, a realistic email will be generated corresponding to the name
        real_city: If True, a real US city's name will be picked up from a list. Otherwise, a fictitious city name will be generated.
        phone_simple: If True, a 10 digit US number in the format xxx-xxx-xxxx will be generated. Otherwise, an international number with different format may be returned.

        Default database and table name will be chosen if not specified by user.
        Primarykey: User can choose a PRIMARY KEY from among the data type fields. If nothing specified, the first data field will be made PRIMARY KEY.

        seed: Currently not used. Uses seed from the pydb class if chosen by user

        """
        self._validate_args(num, fields)

        import sqlite3

        if not db_file:
            conn = sqlite3.connect("NewFakeDB.db")
            c = conn.cursor()
        else:
            conn = sqlite3.connect(str(db_file))
            c = conn.cursor()

        if type(primarykey) != str and primarykey is not None:
            print("Primary key type not identified. Not generating any table")
            return None

        # If primarykey is None, designate the first field as primary key
        if not primarykey:
            table_cols = "(" + str(fields[0]) + " varchar PRIMARY KEY NOT NULL,"
            for col in fields[1:-1]:
                table_cols += str(col) + " varchar,"
            table_cols += str(fields[-1]) + " varchar" + ")"
            # print(table_cols)
        else:
            pk = str(primarykey)
            if pk not in fields:
                print(
                    "Desired primary key is not in the list of fields provided, cannot generate the table!"
                )
                return None

            table_cols = "(" + str(fields[0]) + " varchar, "
            for col in fields[1:-1]:
                if col == pk:
                    table_cols += str(col) + " varchar PRIMARY KEY NOT NULL,"
                else:
                    table_cols += str(col) + " varchar, "
            table_cols += str(fields[-1]) + " varchar" + ")"
            # print(table_cols)

        if not table_name:
            table_name = "Table1"
        else:
            table_name = table_name

        str_drop_table = "DROP TABLE IF EXISTS " + str(table_name) + ";"
        c.execute(str_drop_table)
        str_create_table = (
            "CREATE TABLE IF NOT EXISTS " + str(table_name) + table_cols + ";"
        )
        # print(str_create_table)
        c.execute(str_create_table)

        # Create a temporary df
        temp_df = self.gen_dataframe(
            num=num,
            fields=fields,
            real_email=real_email,
            real_city=real_city,
            phone_simple=phone_simple,
        )
        # Use the dataframe to insert into the table
        for i in range(num):
            str_insert = (
                "INSERT INTO "
                + table_name
                + " VALUES "
                + str(tuple(temp_df.iloc[i]))
                + ";"
            )
            c.execute(str_insert)

        # Commit the insertions and close the connection
        conn.commit()
        conn.close()

    def gen_excel(
        self,
        num=10,
        fields=["name"],
        filename="NewExcel.xlsx",
        real_email=True,
        real_city=True,
        phone_simple=True,
        seed=None,
    ):
        """
        Attempts to create an Excel file using Pandas excel_writer function.
        User can specify various data types to be included as fields.

        Data types available:
        - Name, country, city, real (US) cities, US state, zipcode, latitude, longitude
        - Month, weekday, year, time, date
        - Personal email, official email, SSN
        - Company, Job title, phone number, license plate

        Further choices are following:
        real_email: If True and if a person's name is also included in the fields, a realistic email will be generated corresponding to the name
        real_city: If True, a real US city's name will be picked up from a list. Otherwise, a fictitious city name will be generated.
        phone_simple: If True, a 10 digit US number in the format xxx-xxx-xxxx will be generated. Otherwise, an international number with different format may be returned.

        Default file name will be chosen if not specified by user.

        seed: Currently not used. Uses seed from the pydb class if chosen by user

        """
        self._validate_args(num, fields)

        # Create a temporary dataframe
        temp_df = self.gen_dataframe(
            num=num,
            fields=fields,
            real_email=real_email,
            real_city=real_city,
            phone_simple=phone_simple,
        )
        # Use the dataframe to write to an Excel file using Pandas built-in function
        temp_df.to_excel(filename)

In [5]:
# test Pydb

myDB = Pydb()
fields = ['name', 'street_address', 'city', 'state', 'zipcode', 'country', 'company',
                                         'job_title', 'phone', 'ssn', 'email', 'year', 'weekday',
                                         'date', 'time', 'latitude', 'longitude', 'license_plate']

df = myDB.gen_dataframe(num=100, fields=fields )




df

,name,street_address,city,state,zipcode,country,company,job_title,phone-number,ssn,email,year,weekday,date,time,latitude,longitude,license-plate
0,Jeremy Harvey,861 Charles Mills Suite 231,Del Mar,Nebraska,62493,Lao People's Democratic Republic,Cole-Fisher,"Engineer, maintenance (IT)",627-857-9788,451-64-8879,Jeremy_Harvey@</div>,1997,Friday,2013-04-22,14:08:17,-22.7273815,4.672911,EGB-1428
1,Jacob Sanders,88063 Jeffrey Plaza Suite 501,Westboro,Minnesota,42460,Jersey,"Jackson, Williams and Reynolds",Garment/textile technologist,484-061-8704,399-89-5501,Sanders.Jacob@,1980,Wednesday,2015-02-08,00:56:18,29.8800825,56.040617,8EUO316
2,Dale Williams,18593 Fritz Well,Wiota,Oregon,66541,United States Minor Outlying Islands,"Houston, Brown and Houston",Public house manager,808-525-1032,589-72-1395,DaleWilliams@</div>,1971,Tuesday,1988-02-19,23:08:09,87.053252,16.981199,7FLL471
3,Casey Reed,4800 Lee Green,Neapolis,Arizona,56966,Iceland,"Garcia, Rhodes and Roman",Educational psychologist,546-598-2555,354-24-0030,Reed_Casey@</div>,1970,Sunday,1971-02-21,13:11:30,24.346301,73.603766,1JBW937
4,Raymond Jackson,240 Kane Fort,Roselle Park,Maryland,66933,Tuvalu,"Kelly, Glover and Parker","Exhibitions officer, museum/gallery",855-224-1602,218-34-4152,Raymond_J@,1976,Friday,2002-01-30,06:37:15,-47.7906075,13.401904,2VMX852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Henry Johnson,9411 Wilson River Apt. 550,Corral,North Dakota,17942,Guinea,Lee and Sons,Communications engineer,510-259-6632,746-46-9816,Henry_J@</span>,1979,Saturday,2015-03-22,19:10:30,74.2700385,-58.415497,MLV-3000
96,Kenneth Young,767 Phillip Manors,Altha,California,94245,Gabon,Ward-Harrison,Neurosurgeon,954-838-5975,415-59-4490,Kenneth.Young69@,1999,Sunday,1999-05-31,14:14:05,-0.6869945,-90.937608,4UXT449
97,Jennifer Savage,72758 Alexander Center,Sparksville,Rhode Island,62012,Qatar,"Bates, Chandler and Brown",Building services engineer,434-160-9728,224-29-8629,Jennifer_S@,1999,Tuesday,1986-11-25,08:52:05,74.8406445,81.460355,JZW-7556
98,John Booker,1760 Jamie Islands,Redland,Hawaii,69649,French Southern Territories,Anderson-Koch,Cabin crew,413-898-5336,886-70-8803,"John_Booker@<meta name=""viewport"" content=""wid...",2005,Friday,2013-04-14,21:10:40,52.1877935,-1.836658,1DQV726
99,Andrea Whitehead,05476 Sullivan Bypass Apt. 405,North Fork,Montana,88294,South Africa,"Martin, James and Ramos",Seismic interpreter,484-455-5771,751-82-8654,"Andrea.W@<clipboard-copy role=""menuitem"" class...",1985,Tuesday,1979-07-02,22:59:49,37.8751605,163.077710,5IRT876

In [31]:
from random import random,choice, uniform, randint
import random
from copy import copy
import json

'''
 cree la liste des clients avec les données  suivantes :
  chaque categorie a sa liste de clients avec son comportement individuel
  [ID, isCouple, isCouple_enfant, comportement
  avec comportement = {temps, frequence}
  temps = croisement liste de pas  pour definir si on  cree un panier Jour X (matin et ou soir) 
     warning si comportement vide ou uniquement jour
     
# inutile sauf calcul de generation en automatique et reprise dans la generation



# outil de travail programmation ###

dico_type_comportement = {}

for categorie in liste_ref_client :
    l = categorie.split ('_')
    if l [0] == 'couple' :
        dico_type_comportement [categorie] = {'temps_semaine': comportement_semaine1,
                                              'temps_jour' : comportement_jour1,
                                             'frequence' : frequence1 }
    else :
        dico_type_comportement [categorie] = {'temps_semaine': comportement_semaine2,
                                              'temps_jour' : comportement_jour2,
                                             'frequence' : frequence2 }

'''
### saisie

liste_genre = ["homme",
        "femme",
         "couple",
         "couple_enfant",
         ]

liste_situation = ["cadre_sup",
            "cadre",
            "ouvrier"]

liste_niveau_vie = ['bargain_bas_standart',
                     'bargain_bas_bio',
                     'bargain_moyen_standart',
                     'bargain_moyen_bio',
                     'bargain_haut_standart',
                     'bargain_haut_bio',
                     'normal_bas_standart',
                     'normal_bas_bio',
                     'normal_moyen_standart',
                     'normal_moyen_bio',
                     'normal_haut_standart',
                     'normal_haut_bio']




# a generaliser on peut avoir plusieur comportement type #######################""
# et une liste d'une partie de ces comportements pour chaque type de client
# methode :
# creer la liste des comportements possibles
# faire les listes de choix de comportements
# associer une de ces listes à chaque type de client

# on creer les dico comportements
#saisie
comportement_semaine1 = ['lundi', 'mardi', 'mercredi','jeudi','vendredi']
comportement_jour1 = ['matin', 'apm']
nombreAchat1 = (2,5)

frequence1 = 2
dicoComportement1 = {'temps_semaine': comportement_semaine1,
                      'temps_jour': comportement_jour1,
                      'frequence': frequence1,
                       'nombreAchat' : nombreAchat1}

comportement_semaine2 = ['samedi', 'dimanche',]
comportement_jour2 = ['matin', 'apm']
nombreAchat2 = (3,10)

frequence2 = 1
dicoComportement2 = {'temps_semaine': comportement_semaine2,
                      'temps_jour': comportement_jour2,
                      'frequence': frequence2,
                     'nombreAchat' : nombreAchat2}


# on cree les listes de comportements possibles
#saisie
listedicoComportement1 = [dicoComportement1, dicoComportement1,]
listedicoComportement2 = [dicoComportement2, dicoComportement2,]



# on affecte une des listes à chaque type de client
# saisie
dico_type_comportement = {   'homme_cadre_sup': listedicoComportement2,
                             'homme_cadre': listedicoComportement2,
                             'homme_ouvrier': listedicoComportement2,
                             'femme_cadre_sup': listedicoComportement2,
                             'femme_cadre': listedicoComportement2,
                             'femme_ouvrier': listedicoComportement2,
                             'couple_cadre_sup': listedicoComportement1,
                             'couple_cadre': listedicoComportement1,
                             'couple_ouvrier': listedicoComportement1,
                             'couple_enfant_cadre_sup': listedicoComportement1,
                             'couple_enfant_cadre': listedicoComportement1,
                             'couple_enfant_ouvrier': listedicoComportement1,
                            }

# saisie inverse  type_client liste de groupe de produits 
# niveau de vie à fournir à generation achats
# ainsi que la liste type client et on va genere
# un type de client est associer  à une liste de type de produit
# achat tape dans cette liste pour acceder aux produit et generer un achat pour chaque comportement

dico_ref = {'bargain_bas_standart': 'couple_enfant_ouvrier',
             'bargain_bas_bio': 'couple_enfant_cadre',
             'bargain_moyen_standart': 'couple_enfant_cadre_sup',
             'bargain_moyen_bio': 'couple_ouvrier',
             'bargain_haut_standart': 'couple_cadre',
             'bargain_haut_bio': 'couple_cadre',
             'normal_bas_standart': 'homme_ouvrier',
             'normal_bas_bio': 'femme_ouvrier',
             'normal_moyen_standart': 'homme_cadre',
             'normal_moyen_bio': 'femme_cadre',
             'normal_haut_standart': 'homme_cadre_sup',
             'normal_haut_bio': 'femme_cadre_sup'}




# parametres de generations clients
# saisie 
nombre = 1 # nombre de client genere pour tout les types (ex homme_cadre)
couple = 2 # nombre de client qui se sont declaré en couple
couple_enfant = 3 # nombre de client qui se sont declaré en couple avec enfant
isVerif = True


def genererTypeClient (liste1, liste2) :
    rr = []
    for l1 in liste1 :
        for l2 in liste2 :
            r =  '_'.join([l1,l2])
            rr.append (r)
            continue
        continue
    return rr
            
liste_ref_client = genererTypeClient (liste_genre, liste_situation)









# on calcul la valeur type de client ex "homme_cadre" 
def croisement_temps (liste1, liste2) :
    if liste2 == [] :
        return  liste1
    
    r = []
    for t1 in liste1 :
        for t2 in liste2 :
            tt = '_'.join ([t1,t2])
            r.append(tt)
            continue
        continue
    return r


dico_comportement = {}


for categorie in liste_ref_client :
    liste = dico_type_comportement [categorie]
    # on reduit chaque comportement de la liste
    newListe = []
    for dico in liste :
        temps_semaine = dico ['temps_semaine']
        temps_jour = dico ['temps_jour']
        frequence = dico['frequence']
        nombreAchat = dico ['nombreAchat']
        l = croisement_temps (temps_semaine, temps_jour)
        new_dico = {'temps' : l, 'frequence' : frequence, 'nombreAchat': nombreAchat}
        
        newListe.append(new_dico)
        continue
    dico_comportement [categorie] = newListe
    continue


    
    
    
        
        



# on renverse on obtiend genre => categorie

liste_categorie = list(dico_ref.keys())
dico_ref_client = {}
for categorie in liste_categorie :
    genre_client = dico_ref [categorie]
    dico_ref_client [genre_client ] = categorie
    continue
    
# le comportement voulu depend d etre ou non un couple

def choice (liste) :
    t = len(liste)
    listeIndice = range(0,t)
    try:
        i = random.choice (listeIndice)
    except:
        return None
    return liste [i]

def rechercheComportement (categorie) :
    comportements = dico_comportement [categorie]
    r = choice (comportements)
    return r
    
    

def generationClientType (categorie,
                          nombre,
                          nombre_couple = None,
                          nombre_couple_enfant = None,
                         ):
    
    l = []
    n1 = nombre_couple
    n2 = nombre_couple_enfant
    #print (nombre)
    for i in range (0, nombre ):
        ID = categorie + '_' +str(i)
        # on calcul un client et on l'enregistre dans l
        ll = [ID,]
        if n1 is None :
            ll.append('')
        else :
            if n1 != 0 :
                ll.append ('couple')
                n1 -= 1
                ll.append('')
                comportement = rechercheComportement (categorie)
                ll.append (comportement)
                l.append(ll)
                continue
                
            else:
                ll.append('')
        if n2 is None :
            ll.append('')
        else :
            if n2 != 0 :
                ll.append ('couple_enfant')
                n2 -= 1
                comportement = rechercheComportement (categorie)
                ll.append (comportement)
                l.append(ll)
                continue
            else:
                ll.append('')
            
        
        
        comportement = rechercheComportement (categorie)
        ll.append (comportement)
        l.append(ll)
        #print ("i =",i," et taille client =", len(ll))
        continue
    random.shuffle(l)
    return l

#  en nombre pour obtenir l'ensemble des clients warning (le comportement depend de couple ou pas)
def generationClient(nombre, couple = None, couple_enfant = None) :
    
    dico = {}
    for categorie in liste_ref_client :
        cc = categorie.split('_')
        c = ''
        if cc [0] == 'couple' :
            if cc [1] == 'enfant' :
                c = 'couple_enfant'
            else:
                c = 'couple'
        
        if c == 'couple' :
            nombre_couple = couple
        else:
            nombre_couple = None
        
        if c == 'couple_enfant' :
            nombre_couple_enfant = couple_enfant
        else:
            nombre_couple_enfant = None
            
        #print (nombre)
        l = generationClientType (categorie,
                                  nombre,
                                  nombre_couple = nombre_couple,
                                  nombre_couple_enfant = nombre_couple_enfant,
                         )
        
        
        dico [categorie] = l
        continue
    return dico



# chaque categorie a sa liste de clients avec son comportement individuel
# [ID, isCouple, isCouple_enfant, comportement
# comportement = {temps, frequence}
# temps = croisement Jour X (matin et ou soir) 
#warning si comportement vide ou uniquement jour
isVerif = True
nombreDeRepetition = 2
dico = generationClient(nombreDeRepetition, couple = couple, couple_enfant = couple_enfant)

# on sauve en json
data = json.dumps (dico)
nomFile = "../data/generation/dico_client.json"
f = open (nomFile , 'w')
f.write (data)
f.close()

# on verifie

nomFile = "../data/generation/dico_client.json"
f = open (nomFile , 'r')
dicoLu = json.loads(f.read ())
f.close()
nombreLu = 0
nombreCategorie = 0
if isVerif :
    print ("#### verification")
    for categorie in liste_ref_client :
        liste_client = dicoLu [categorie]
        #print ("## ", categorie)
        for client in liste_client:
            #print ("   ", client)
            nombreLu += 1
            continue
        nombreCategorie += 1
        
        continue
    if nombreCategorie  !=  12 :
        print ("erreur nombre de categorie client  =", nombreCategorie)

    if nombreDeRepetition * 12 != nombreLu :
        print ("erreur nombre de generation =", nombreDeRepetition*12," !=" ,nombreLu)
    
if isVerif :
    print ("verification OK")
else :
    print ("generation OK")

#### verification
verification OK

In [54]:
liste_genre = ["homme",
        "femme",
         "couple",
         "couple_enfant",
         ]

liste_situation = ["cadre_sup",
            "cadre",
            "ouvrier"]

def genererTypeClient (liste1, liste2) :
    rr = []
    for l1 in liste1 :
        for l2 in liste2 :
            r =  '_'.join([l1,l2])
            rr.append (r)
            continue
        continue
    return rr
            
rr = genererTypeClient (liste_genre, liste_situation)            
rr

['homme_cadre_sup',
 'homme_cadre',
 'homme_ouvrier',
 'femme_cadre_sup',
 'femme_cadre',
 'femme_ouvrier',
 'couple_cadre_sup',
 'couple_cadre',
 'couple_ouvrier',
 'couple_enfant_cadre_sup',
 'couple_enfant_cadre',
 'couple_enfant_ouvrier']

In [53]:
dico_ref = {'bargain_bas_standart': 'couple_enfant_ouvrier',
 'bargain_bas_bio': 'couple_enfant_cadre',
 'bargain_moyen_standart': 'couple_enfant_cadre_sup',
 'bargain_moyen_bio': 'couple_ouvrier',
 'bargain_haut_standart': 'couple_cadre',
 'bargain_haut_bio': 'couple_cadre',
 'normal_bas_standart': 'homme_ouvrier',
 'normal_bas_bio': 'femme_ouvrier',
 'normal_moyen_standart': 'homme_cadre',
 'normal_moyen_bio': 'femme_cadre',
 'normal_haut_standart': 'homme_cadre_sup',
 'normal_haut_bio': 'femme_cadre_sup'}

[x for x in dico_ref.keys()]

['bargain_bas_standart',
 'bargain_bas_bio',
 'bargain_moyen_standart',
 'bargain_moyen_bio',
 'bargain_haut_standart',
 'bargain_haut_bio',
 'normal_bas_standart',
 'normal_bas_bio',
 'normal_moyen_standart',
 'normal_moyen_bio',
 'normal_haut_standart',
 'normal_haut_bio']

In [37]:
d = [None]
x = json.dumps (d)
r = json.loads (x)
r

[None]

In [42]:
def choice (liste) :
    t = len(liste)
    listeIndice = range(0,t)
    try:
        i = random.choice (listeIndice)
    except:
        return None
    return liste [i]


l = ['nn1', 'ee1']
r = choice (l)
print (r)
s = ""
for _ in range(0,10) :
    l = ['nn2', 'ee2', 'zz2']
    r = choice (l)
    s +=r+" "
print (s)

l = ['11']
r = choice (l)
print (r)

l = []
r = choice (l)
print (r)

nn1
nn2 ee2 zz2 nn2 zz2 ee2 ee2 zz2 ee2 zz2
11
None

In [24]:
def croisement_temps (liste1, liste2) :
    if liste2 == [] :
        return  liste1
    
    r = []
    for t1 in liste1 :
        for t2 in liste2 :
            tt = '_'.join ([t1,t2])
            r.append(tt)
            continue
        continue
    return r

r = croisement_temps (comportement_semaine1, comportement_jour1) 
print (r)
print ()
r = croisement_temps (comportement_semaine1, [])
print (r)
print ()
r = croisement_temps ([], comportement_jour1) 
print (r)
print ()
r = croisement_temps ([], []) 
print (r)
print ()

['lundi_matin', 'lundi_apm', 'mardi_matin', 'mardi_apm', 'mercredi_matin', 'mercredi_apm', 'jeudi_matin', 'jeudi_apm', 'vendredi_matin', 'vendredi_apm']

['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi']

[]

[]

In [26]:


            


def croisement_temps (liste1, liste2) :
    if liste2 == [] :
        return  liste1
    
    r = []
    for t1 in liste1 :
        for t2 in liste2 :
            tt = '_'.join ([t1,t2])
            r.append(tt)
            continue
        continue
    return r
        

dico_comportement = {}

for categorie in liste_ref_client :
    dico = dico_type_comportement [categorie]
    temps_semaine = dico ['temps_semaine']
    temps_jour = dico ['temps_jour']
    frequence = dico['frequence']
    l = croisement_temps (temps_semaine, temps_jour)
    dico_comportement [categorie] = {'temps' : l, 'frequence' : frequence}
    continue


        
dico_comportement

{'homme_cadre_sup': {'temps': ['samedi_matin',
   'samedi_apm',
   'dimanche_matin',
   'dimanche_apm'],
  'frequence': 1},
 'homme_cadre': {'temps': ['samedi_matin',
   'samedi_apm',
   'dimanche_matin',
   'dimanche_apm'],
  'frequence': 1},
 'homme_ouvrier': {'temps': ['samedi_matin',
   'samedi_apm',
   'dimanche_matin',
   'dimanche_apm'],
  'frequence': 1},
 'femme_cadre_sup': {'temps': ['samedi_matin',
   'samedi_apm',
   'dimanche_matin',
   'dimanche_apm'],
  'frequence': 1},
 'femme_cadre': {'temps': ['samedi_matin',
   'samedi_apm',
   'dimanche_matin',
   'dimanche_apm'],
  'frequence': 1},
 'femme_ouvrier': {'temps': ['samedi_matin',
   'samedi_apm',
   'dimanche_matin',
   'dimanche_apm'],
  'frequence': 1},
 'couple_cadre_sup': {'temps': ['lundi_matin',
   'lundi_apm',
   'mardi_matin',
   'mardi_apm',
   'mercredi_matin',
   'mercredi_apm',
   'jeudi_matin',
   'jeudi_apm',
   'vendredi_matin',
   'vendredi_apm'],
  'frequence': 2},
 'couple_cadre': {'temps': ['lundi_matin',
   'lundi_apm',
   'mardi_matin',
   'mardi_apm',
   'mercredi_matin',
   'mercredi_apm',
   'jeudi_matin',
   'jeudi_apm',
   'vendredi_matin',
   'vendredi_apm'],
  'frequence': 2},
 'couple_ouvrier': {'temps': ['lundi_matin',
   'lundi_apm',
   'mardi_matin',
   'mardi_apm',
   'mercredi_matin',
   'mercredi_apm',
   'jeudi_matin',
   'jeudi_apm',
   'vendredi_matin',
   'vendredi_apm'],
  'frequence': 2},
 'couple_enfant_cadre_sup': {'temps': ['lundi_matin',
   'lundi_apm',
   'mardi_matin',
   'mardi_apm',
   'mercredi_matin',
   'mercredi_apm',
   'jeudi_matin',
   'jeudi_apm',
   'vendredi_matin',
   'vendredi_apm'],
  'frequence': 2},
 'couple_enfant_cadre': {'temps': ['lundi_matin',
   'lundi_apm',
   'mardi_matin',
   'mardi_apm',
   'mercredi_matin',
   'mercredi_apm',
   'jeudi_matin',
   'jeudi_apm',
   'vendredi_matin',
   'vendredi_apm'],
  'frequence': 2},
 'couple_enfant_ouvrier': {'temps': ['lundi_matin',
   'lundi_apm',
   'mardi_matin',
   'mardi_apm',
   'mercredi_matin',
   'mercredi_apm',
   'jeudi_matin',
   'jeudi_apm',
   'vendredi_matin',
   'vendredi_apm'],
  'frequence': 2}}

In [35]:
categorie = 'couple-enfant_ouvrier'
nombre = 10
nombre_couple = 2
nombre_couple_enfant = 2



l = generationClientType (categorie,
                          nombre,
                          nombre_couple = nombre_couple ,
                          nombre_couple_enfant = nombre_couple_enfant,
                         )

l

[['couple-enfant_ouvrier_0', 'couple', ''],
 ['couple-enfant_ouvrier_8', '', ''],
 ['couple-enfant_ouvrier_4', '', ''],
 ['couple-enfant_ouvrier_9', '', ''],
 ['couple-enfant_ouvrier_7', '', ''],
 ['couple-enfant_ouvrier_1', 'couple', ''],
 ['couple-enfant_ouvrier_3', '', 'couple_enfant'],
 ['couple-enfant_ouvrier_5', '', ''],
 ['couple-enfant_ouvrier_2', '', 'couple_enfant'],
 ['couple-enfant_ouvrier_6', '', '']]

In [31]:
nombre = 10
couple = 2
couple_enfant = 3

dico =generationClient(nombre, couple = couple, couple_enfant = couple_enfant)

dico

{'homme_cadre_sup': [['homme_cadre_sup_9', '', ''],
  ['homme_cadre_sup_1', '', ''],
  ['homme_cadre_sup_2', '', ''],
  ['homme_cadre_sup_4', '', ''],
  ['homme_cadre_sup_7', '', ''],
  ['homme_cadre_sup_0', '', ''],
  ['homme_cadre_sup_3', '', ''],
  ['homme_cadre_sup_5', '', ''],
  ['homme_cadre_sup_8', '', ''],
  ['homme_cadre_sup_6', '', '']],
 'homme_cadre': [['homme_cadre_4', '', ''],
  ['homme_cadre_0', '', ''],
  ['homme_cadre_6', '', ''],
  ['homme_cadre_2', '', ''],
  ['homme_cadre_1', '', ''],
  ['homme_cadre_7', '', ''],
  ['homme_cadre_5', '', ''],
  ['homme_cadre_9', '', ''],
  ['homme_cadre_3', '', ''],
  ['homme_cadre_8', '', '']],
 'homme_ouvrier': [['homme_ouvrier_3', '', ''],
  ['homme_ouvrier_6', '', ''],
  ['homme_ouvrier_7', '', ''],
  ['homme_ouvrier_8', '', ''],
  ['homme_ouvrier_4', '', ''],
  ['homme_ouvrier_5', '', ''],
  ['homme_ouvrier_0', '', ''],
  ['homme_ouvrier_1', '', ''],
  ['homme_ouvrier_2', '', ''],
  ['homme_ouvrier_9', '', '']],
 'femme_cadre_sup': [['femme_cadre_sup_6', '', ''],
  ['femme_cadre_sup_1', '', ''],
  ['femme_cadre_sup_0', '', ''],
  ['femme_cadre_sup_2', '', ''],
  ['femme_cadre_sup_3', '', ''],
  ['femme_cadre_sup_7', '', ''],
  ['femme_cadre_sup_9', '', ''],
  ['femme_cadre_sup_5', '', ''],
  ['femme_cadre_sup_8', '', ''],
  ['femme_cadre_sup_4', '', '']],
 'femme_cadre': [['femme_cadre_6', '', ''],
  ['femme_cadre_1', '', ''],
  ['femme_cadre_8', '', ''],
  ['femme_cadre_5', '', ''],
  ['femme_cadre_0', '', ''],
  ['femme_cadre_7', '', ''],
  ['femme_cadre_3', '', ''],
  ['femme_cadre_4', '', ''],
  ['femme_cadre_2', '', ''],
  ['femme_cadre_9', '', '']],
 'femme_ouvrier': [['femme_ouvrier_7', '', ''],
  ['femme_ouvrier_2', '', ''],
  ['femme_ouvrier_1', '', ''],
  ['femme_ouvrier_4', '', ''],
  ['femme_ouvrier_5', '', ''],
  ['femme_ouvrier_9', '', ''],
  ['femme_ouvrier_8', '', ''],
  ['femme_ouvrier_0', '', ''],
  ['femme_ouvrier_6', '', ''],
  ['femme_ouvrier_3', '', '']],
 'couple_cadre_sup': [['couple_cadre_sup_5', '', ''],
  ['couple_cadre_sup_4', '', ''],
  ['couple_cadre_sup_1', 'couple', ''],
  ['couple_cadre_sup_3', '', ''],
  ['couple_cadre_sup_8', '', ''],
  ['couple_cadre_sup_9', '', ''],
  ['couple_cadre_sup_6', '', ''],
  ['couple_cadre_sup_2', '', ''],
  ['couple_cadre_sup_7', '', ''],
  ['couple_cadre_sup_0', 'couple', '']],
 'couple_cadre': [['couple_cadre_3', '', ''],
  ['couple_cadre_1', 'couple', ''],
  ['couple_cadre_4', '', ''],
  ['couple_cadre_2', '', ''],
  ['couple_cadre_0', 'couple', ''],
  ['couple_cadre_9', '', ''],
  ['couple_cadre_6', '', ''],
  ['couple_cadre_5', '', ''],
  ['couple_cadre_7', '', ''],
  ['couple_cadre_8', '', '']],
 'couple_ouvrier': [['couple_ouvrier_4', '', ''],
  ['couple_ouvrier_5', '', ''],
  ['couple_ouvrier_3', '', ''],
  ['couple_ouvrier_6', '', ''],
  ['couple_ouvrier_0', 'couple', ''],
  ['couple_ouvrier_7', '', ''],
  ['couple_ouvrier_2', '', ''],
  ['couple_ouvrier_1', 'couple', ''],
  ['couple_ouvrier_9', '', ''],
  ['couple_ouvrier_8', '', '']],
 'couple_enfant_cadre_sup': [['couple_enfant_cadre_sup_5', '', ''],
  ['couple_enfant_cadre_sup_9', '', ''],
  ['couple_enfant_cadre_sup_7', '', ''],
  ['couple_enfant_cadre_sup_6', '', ''],
  ['couple_enfant_cadre_sup_3', '', ''],
  ['couple_enfant_cadre_sup_1', '', 'couple_enfant'],
  ['couple_enfant_cadre_sup_0', '', 'couple_enfant'],
  ['couple_enfant_cadre_sup_4', '', ''],
  ['couple_enfant_cadre_sup_2', '', 'couple_enfant'],
  ['couple_enfant_cadre_sup_8', '', '']],
 'couple_enfant_cadre': [['couple_enfant_cadre_5', '', ''],
  ['couple_enfant_cadre_9', '', ''],
  ['couple_enfant_cadre_6', '', ''],
  ['couple_enfant_cadre_1', '', 'couple_enfant'],
  ['couple_enfant_cadre_2', '', 'couple_enfant'],
  ['couple_enfant_cadre_4', '', ''],
  ['couple_enfant_cadre_7', '', ''],
  ['couple_enfant_cadre_3', '', ''],
  ['couple_enfant_cadre_0', '', 'couple_enfant'],
  ['couple_enfant_cadre_8', '', '']],
 'couple_enfant_ouvrier': [['couple_enfant_ouvrier_0', '', 'couple_enfant'],
  ['couple_enfant_ouvrier_4', '', ''],
  ['couple_enfant_ouvrier_1', '', 'couple_enfant'],
  ['couple_enfant_ouvrier_7', '', ''],
  ['couple_enfant_ouvrier_3', '', ''],
  ['couple_enfant_ouvrier_2', '', 'couple_enfant'],
  ['couple_enfant_ouvrier_8', '', ''],
  ['couple_enfant_ouvrier_6', '', ''],
  ['couple_enfant_ouvrier_5', '', ''],
  ['couple_enfant_ouvrier_9', '', '']]}

In [34]:
bargain = ['bargain',
          'normal',]
bio = ['standart','bio',
      ]

gamme = ['bas',
         'moyen',
         'haut',
         ]


bio_haut_normal = 71
bio_haut_bargain = 61
bio_moyen_bargain = 51
bio_moyen_normal = 61
bio_bas_normal = 51
bio_bas_bargain = 41




bio_haut_normal = 71

standart_haut_normal = 61
standart_haut_bargain = 51
standart_moyen_bargain = 41
standart_bas_bargain = 31
standart_haut_normal = 61
standart_moyen_normal = 51
standart_bas_normal = 41

dico = {}
low = 1
for bargain1 in bargain:
    for gamme1 in gamme:
        for bio1 in bio :
            s = "_".join ([bargain1, gamme1, bio1])
            dico [s] = (low, low+10)
            low += 11
            
            

            
                
dico

{'bargain_bas_standart': (1, 11),
 'bargain_bas_bio': (12, 22),
 'bargain_moyen_standart': (23, 33),
 'bargain_moyen_bio': (34, 44),
 'bargain_haut_standart': (45, 55),
 'bargain_haut_bio': (56, 66),
 'normal_bas_standart': (67, 77),
 'normal_bas_bio': (78, 88),
 'normal_moyen_standart': (89, 99),
 'normal_moyen_bio': (100, 110),
 'normal_haut_standart': (111, 121),
 'normal_haut_bio': (122, 132)}

In [1]:
from random import random,choice, uniform
low = 1
hight = 10
p = uniform (low*100., hight*100.)
int (p)/100.

6.07

In [20]:
copy (['eee'])

TypeError: 'module' object is not callable